apiVersion: v1
kind: Namespace
metadata:
  name: security-platform
  labels:
    # PodSecurity admission — enforce restricted profile
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.28
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.28
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.28
    app.kubernetes.io/managed-by: kubectl
    environment: production
